### ISSUE TITLE
The token should look like this

### ISSUE THREAD

**Issue by MarcOlle** [0xf4b1/hearthstone-linux#1]
I just managed to do all steps on the README, but the token I got is different from the token that is required. My account ID has one less number than it is set on the token.exe. My account ID looks like this: YYYYYYYY. So when I put the token I got it doesn't works.
Example Token:
`XX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXX`
My token:
`XX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-YYYYYYYY`

**Comment by 0xf4b1** [comment]
Hm okay, sounds like the tokens can be different in size, mine has definitely one more number. Actually I have only added a very small check for the token size in the Token.cs file:

`if (args[0].Length != 45) {
Console.WriteLine("The token should look like this: XX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXX");
Environment.Exit(-1);
}`

Is it working when you simply remove that part and rebuild?
