### ISSUE TITLE
mono linux player not found

### ISSUE THREAD

**Issue by coocoorhin** [0xf4b1/hearthstone-linux#2]
when i run the "craft.sh" i have encountered this error 
`cp: cannot stat '/home/ziyao/Unity-2018.4.10f1/Hub/Editor/2018.4.10f1/Editor/Data/PlaybackEngines/LinuxStandaloneSupport/Variations/linux64_withgfx_nondevelopment_mono/LinuxPlayer': No such file or directory`

i have the latest version of hearthstone installed using `ngdp` and unity version `Unity-2018.4.10f1`
what seems to be the problem?

**Comment by 0xf4b1** [comment]
It looks like you are missing the engine files? After downloading the `UnityHub.AppImage`, do you have installed the engine files `2018.4.10f1`?

I just tried it and it works for me like this:
- Make the file executable
`chmod +x ./UnityHub.AppImage`
- Start unity hub with the url
`./UnityHub.AppImage unityhub://2018.4.10f1/a0470569e97b`
- You can ignore the licensing stuff that may show up, wait until the installation window appears. You don't need to install any of the additional modules.
