### ISSUE TITLE
When generating a new token, null username is used

### ISSUE THREAD

**Issue by Ilia1** [0xf4b1/hearthstone-linux#26]
Before version 23.6 the game was installed and started. I downloaded the latest version of scripts from this repository. The game stopped running. I tried clearing all folders and installing again. It did not help. At startup, no logs are displayed and the logs folder is not created. Launch looks like this
```
ilia:hearthstone> ./Bin/Hearthstone.x86_64 
ilia:hearthstone> 
```

**Comment by 0xf4b1** [comment]
hmm, does the binary instantly terminate? Based on this limited information, I can only make assumptions. Did you make sure that it uses the latest version of the unity stuff?

**Comment by Ilia1** [comment]
I believe the latest version is loaded by the craft.sh script. I completely cleared the game folder and ran this script.

**Comment by 0xf4b1** [comment]
If the script was downloading the unity files, then it will be the correct version. If the files were already present in the directories the script is looking into (tmp/Unity.tar.xz or ~/Unity/Hub...), then i think it could use older ones since there is no version checking for that.

**Comment by Ilia1** [comment]
I deleted ~/Unity/Hub, tmp, hearthstone folder and download everything again. No result.
I noticed that the file Hearthstone.x86_64 in the previous version was taking up space 26M, current 6K. It`s normal?

**Comment by 0xf4b1** [comment]
Yes, that's normal. I think they moved a lot of the stuff into `UnityPlayer.so` which should be in the same directory.

**Comment by Ilia1** [comment]
I apologize for the long reply. I ran strace and found out that the library is missing `Bin/Hearthstone_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so`
I copied the x86_64 folder from the Mono folder and everything ran.

**Comment by 0xf4b1** [comment]
Hm, maybe the missing library was due to an existing folder of an older version of the unity files? Anyway, for the login, do you have updated and made sure the new stub `libblz_commerce_sdk_plugin.so` is present? If yes, have a look and share the logs, so that we can have a look what's going on.

**Comment by Ilia1** [comment]
[hearthstone.log](https://gist.github.com/Ilia1/cc9107450ed645c71a770bb89c2b5023)

**Comment by 0xf4b1** [comment]
From the log, I can see something is wrong with your login. Either the token file is not present or invalid, or if you created a new account, you need to login once into battle.net and accept the terms dialog.

**Comment by Ilia1** [comment]
Token.exe was missing from the hearthstone folder for some reason. Now the token was generated correctly.

**Comment by 0xf4b1** [comment]
Actually the Token.exe is no longer needed for the login app anymore and therefore not copied into the game directory anymore.

**Comment by Ilia1** [comment]
I'm on the master branch. The token was created when I used the `login` program. There was an authorization error with this token. When I created the token with `Token.exe`, the authorization was successful.

**Comment by 0xf4b1** [comment]
This is strange, the created token from the login app works fine for me, also when I try a different account. Not sure if it's for some reason extracting the token wrong for you? Did you used the printed "Found token: " from the login app and then created it with the Token.exe? Then we can see if the login app extracted it correctly.

**Comment by Ilia1** [comment]
> Did you used the printed "Found token: " from the login app and then created it with the Token.exe?

Yes

**Comment by 0xf4b1** [comment]
Could you `diff` both tokens so see if they have any difference? When I create the token with the login app, rename it to `token.bak` and create the printed token with Token.exe again, `diff token token.bak` shows they are identical

**Comment by Ilia1** [comment]
```
md5sum token*
2b93d26b379b252ee4b921ded69a1ee7  token
13528ef132a50fdf2eb727fedbc4d43b  token.bak
```
I don't know if it's important or not, but I also have two-factor authorization enabled

**Comment by 0xf4b1** [comment]
Hm, since both files differ, something must be wrong in the login app for you. For a given token, both the login app and the Token.exe must produce the same output. Unfortunately, I can not reproduce this and don't know the problem :(

**Comment by Ilia1** [comment]
I have found [the cause of the problem](https://stackoverflow.com/questions/35068592/getlogin-r-and-getlogin-do-only-work-on-tty). Function getlogin_r() may not work properly. I checked the function in mate terminal and it returned null. But in tty it return name.

**Comment by 0xf4b1** [comment]
Thank you for spotting this, I've replaced getlogin_r() with the proposed alternative and hope the login now works for you.

**Comment by Ilia1** [comment]
Thank you. Now the token is correct and login works.
