### ISSUE TITLE
can't figure out how to login

### ISSUE THREAD

**Issue by HliasOuzounis** [0xf4b1/hearthstone-linux#27]
I'm running on arch, the installation was successful and I can launch `Bin/Hearthstone.x86_64`
but the games kicks me out cause I was not able to login through the blizzard services.
I tried running the **login** executable (_both in the /hearthstone and in the /login folder_) but it does nothing, without any errors or outputs. 
I also tried to login in manually as per the README file. But the [link](https://eu.battle.net/login/en/?app=wtcg) I followed goes to a website that doesn't load and I can't login in through that either.

**Comment by 0xf4b1** [comment]
Does https://battle.net/login/?app=wtcg work for you? The login app should only pop up a small window and display this page asking for username and password and save the login token after logging in.

**Comment by HliasOuzounis** [comment]
Unfortunately not. I'm greeted with a blank page and nothing pops up. Could this be a problem with my tiling manager (qtile)? Perhaps it loads but doesn't appear on screen? Truth is I'm a new linux user so please be patient with me.

**Comment by 0xf4b1** [comment]
So the page is not reachable even through your normal webbrowser? If not, something else must be wrong I think.. Does logging into battle.net/login work?

**Comment by HliasOuzounis** [comment]
Yeah, I tried it through firefox. I am able to login to battlenet (the web page).

**Comment by 0xf4b1** [comment]
If you are already logged in when trying to visit https://battle.net/login/?app=wtcg, you should get this immediate redirect as described in the README with the token in the address bar. Otherwise you could also try to open that page without cookies in incognito mode.

**Comment by HliasOuzounis** [comment]
I opened it in a private window and finally saw the login page in the browser, not a popup. I entered my credentials but it's been 5 minutes and it's still loading. I believe my connection works just fine.
Maybe a dumb question, but am I supposed to have the battlenet client downloaded or something similar?

**Comment by 0xf4b1** [comment]
I was using chromium... I just tested with firefox and it seems to behave differently, it does not follow the redirect. But you can still get the redirect url if you open dev tools (F12) and go to the network tab, then login and find it in the response headers in the location field. Or since it sets a cookie, look for the gs-hs cookie in storage tab

**Comment by HliasOuzounis** [comment]
I opened it with chromium and generated my token :+1: . Now when I open the hearthstone app I get an unable to connect, check your internet connection message.
I'm so sad, I thought I had it this time.

**Comment by 0xf4b1** [comment]
If you created the token with `mono token.exe <token>` and it said "Created token", then it should be fine. You probably only need to move the created file `token` into the hearthstone directory.

**Comment by HliasOuzounis** [comment]
yep, now it works. Thanks so much

**Comment by 0xf4b1** [comment]
Cool, I'm glad that it works for you now :) However, not sure why the login app does not work for you, it should make it easier.
