### ISSUE TITLE
[Suggestion] Use MPQ instead NGDP

### ISSUE THREAD

**Issue by Ilia1** [0xf4b1/hearthstone-linux#29]
Tool for extracting MPQ file https://github.com/Kanma/MPQExtractor
Example how to get download url  https://github.com/jleclanche/patchtools
Example url http://dist.blizzard.com.edgesuite.net/hs-pod/beta/NA/4944.direct/base-OSX.MPQ

**Comment by 0xf4b1** [comment]
I assume you want to find a replacement for keg to download and update the game? Are you able to get a full working installation with only using the links you posted?

**Comment by Ilia1** [comment]
It seems that only the old version of 2015 is available in the MPQ
