### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by bourrinlepoulpe** [0xf4b1/hearthstone-linux#31]
Hello I can't seem to login, did something change ? I can't even retrieve the token, the somethingWTCG url hangs after login been typed in. I tried by terminal and it says incorrect 
Is this an issue on their end ?

**Comment by 0xf4b1** [comment]
Have you tried the `login` app? If you get it manually, it works for me as described with chromium, but firefox hangs (and tries to follow the redirect).

**Comment by bourrinlepoulpe** [comment]
The login app doesn't open, it asks for privilege elevation, and sudo login appears in the terminal, but it won't accept my battlenet login credentials.

**Comment by 0xf4b1** [comment]
something must be wrong for you, the app should not need and not ask for privileges. also I don't really understand what you mean with appears in terminal, it should only show a small window that contains this wtcg website. If the webpage says the credentials are wrong, then maybe try to verify you can login on battle.net

**Comment by bourrinlepoulpe** [comment]
I mean nothing pops up from the terminal, then a line appears saying it needs privilege to work.
heres the terminal : 
aurelien@aurelien-lifebooke752:~$ cd hearthstone-linux/
aurelien@aurelien-lifebooke752:~/hearthstone-linux$ login
login: Cannot possibly work without effective root
aurelien@aurelien-lifebooke752:~/hearthstone-linux$ sudo login
aurelien-lifebooke752 login: something@something.com
Password: 

Login incorrect
aurelien-lifebooke752 login: 



I tried many many times my credentials, and they work on other devices

**Comment by 0xf4b1** [comment]
I think you are executing the login binary from your system, not from the hearthstone directory, try `./login` instead :)

**Comment by bourrinlepoulpe** [comment]
Oh I see, I'll reinstall and check it out :) thanks

**Comment by 0xf4b1** [comment]
so when the token file is now present in the hearthstone directory, how do you run the game? Have you tried the launcher? From terminal, make sure to cd into the hearthstone directory and run `Bin/hearthstone.x86_64`

**Comment by bourrinlepoulpe** [comment]
Yes I do launch from the directory, the game comes up but I have an error, 
[url=https://ibb.co/71KkW8z][img]https://i.ibb.co/71KkW8z/Screenshot-20221229-121110.png[/img][/url]
From what I could gatherI ve checked my firewall etc but nothing on this side

**Comment by 0xf4b1** [comment]
It's important that your cwd is the hearthstone directory where the token file is located and you run with `Bin/Hearthstone.x86_64`. have you done it like this? Also please try the created launcher in your desktop environment

**Comment by bourrinlepoulpe** [comment]
I don't have any launcher created, using kubuntu btw. and yes I cd to the directory and ./Bin/Hearthstone.x86_64 I ve tried from the bin directory itself, from ~ too.
Also I checked inside the craft script but I don't have any ./local/share/application folder

**Comment by bourrinlepoulpe** [comment]
I deleted the whole HS folder, created manually the ~/.local/share/applications one then lanch the reinstall to see if it changes something

**Comment by 0xf4b1** [comment]
There are multiple possible reasons for this error message unfortunately. If the script executed successfully, the only two reasons I'm aware of that cause this error message are the token file is missing/invalid in the hearthstone directory or the game was not started the way as described. Maybe try to login again (make sure to use the login binary in the hearthstone directory, not in the login folder). Have you played the game on an official client recently with your account? Maybe you have to accept some new teams that are not showing up here. You could also try to create a new account to test, for me I can login with it

**Comment by bourrinlepoulpe** [comment]
So having created the application folder within the .local/share, made the script create the .desktop file.
Still no luck though, I can use my account on all my other devices so I'll keep at it. The script in the console did mention that the token was retrieved though

**Comment by 0xf4b1** [comment]
You could try the manual described approach to get the token. You would need to build the token tool in the token folder with mcs and then run `mono Token.exe <insert token here>` and move the created token file into the hearthstone directory
