### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by boberooskie** [0xf4b1/hearthstone-linux#32]
This method worked great until about a week ago now, now im only met with an error message when trying to log in.
"CLOSED, the game was unable to log you in through the blizzzard services. Please wait a few minutes and try again"

**Comment by Ice2501** [comment]
Fwiw I cannot reproduce this, works as intended for me. Maybe your token expired?

**Comment by 0xf4b1** [comment]
Also working fine for me, I'm not really sure what this problem is about because there are multiple issues already describing login issues :thinking:
