### ISSUE TITLE
unable to launch

### ISSUE THREAD

**Issue by ginop-1** [0xf4b1/hearthstone-linux#34]
Hi, I'm trying to launch heartstone but this is the output I'm receiving:

The output from craft.sh:

```
Region: eu
Online version: 25.6.0.168788
Downloaded version: 25.6.0.168788
Moving files & running cleanup ...

mv: cannot stat '.../hearthstone-linux/hearthstone/Hearthstone.app/Contents/Resources/Data': No such file or directory
```

Launch behavior:

https://user-images.githubusercontent.com/69142763/225615976-48dee0cd-a36c-4680-a2b4-cc32285f1019.mp4

I have already tried to reinstall the game from scratch, but it hasn't work.

Thanks

**Comment by 0xf4b1** [comment]
Hey, I've checked it today after updating to the most recent version and it still works for me without any changes needed. Are you stuck in this white screen like in the video when running the game? If it is showing something like "Closed, Oops! ...", then the problem that you need to run it from terminal from within the game directory, so instead `./hearthstone/Bin/Hearthstone.x86_64` you need `cd hearthstone` and then `./Bin/Hearthstone.x86_64`

**Comment by ginop-1** [comment]
It's just a white screen without any message. If I don't touch anything it remains in there. I'm starting to think it's a graphical problem, but I don't have any logs.

**Comment by 0xf4b1** [comment]
The script is normal, it should download everything and rearrange the structure as needed. If you run it multiple times while there is no new version, it skips the download but still tries to rearrange everything what was already done before, but this is no problem as it stops immediately.

I can not remember ever having just a white screen... maybe have some logs in `hearthstone/Bin/Logs` directory? I think this could help to identify whats going on.
Also if you suspect something went wrong when you first ran the script, you can try to set everything up again by deleting the `.version` file in the hearthstone directory. Then it should cleanup the game folder again and reinstall (without redownloading everything agian) and do the rearrangements as needed. The script should run through cleanly in this case

**Comment by ginop-1** [comment]
Sorry for the late response.
After deleting .version file and re-running craft.sh, that's a log i found:
https://pastebin.com/EZYKfAuP

**Comment by 0xf4b1** [comment]
The log doesn't contain any issues, it looks pretty much identical compared to mine. Maybe you can verify that other graphical applications work on your system or test with another system

**Comment by ginop-1** [comment]
Seems like a machine problem, not a software bug.

https://user-images.githubusercontent.com/69142763/226186016-02a35b5d-4f34-4c97-9619-7b4f88a6f5de.mp4

If anyone has any ideas, please tell me. If not I'm going to close the issue as it's not related to the game itself
