### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by enyzzz** [0xf4b1/hearthstone-linux#35]
Hello, any idea how to update the app as the new update came out? Sorry I'm a newbie, but I've never had a better experience with Hearthstone on Linux, so I desire to carry this on :)

**Comment by 0xf4b1** [comment]
You only need to run the `./craft` script again :)

**Comment by enyzzz** [comment]
Thank you man, keep up the good work! Is there any way to leave you a donation? at least symbolic :)

**Comment by 0xf4b1** [comment]
hehe, thank you! You are the first to ask this question, currently there is no way to do this :)
