### ISSUE TITLE
looks like the Unity version changed with 26.2

### ISSUE THREAD

**Issue by rayraiani** [0xf4b1/hearthstone-linux#37]
2021.3.19f1 (maybe)
```
$ git diff
diff --git a/craft.sh b/craft.sh
index ee439a2..bb7e81a 100755
--- a/craft.sh
+++ b/craft.sh
@@ -76,7 +76,7 @@ download_hearthstone() {
 }

 UNITY_ENGINE=Editor/Data/PlaybackEngines/LinuxStandaloneSupport/Variations/linux64_withgfx_nondevelopment_mono
-UNITY_VER=2019.4.37f1
+UNITY_VER=2021.3.19f1
 UNITY_INSTALLER_URL=https://download.unity3d.com/download_unity/019e31cfdb15/LinuxEditorInstaller/Unity.tar.xz
 UNITY_HUB=/Hub/Editor/$UNITY_VER/$UNITY_ENGINE
```

**Comment by ApatheticSheep** [comment]
NVM, it core dumped again. maybe not that version or something else.

**Comment by jbakes89** [comment]
I believe you need to change the following lines:

```
78 UNITY_ENGINE=Editor/Data/PlaybackEngines/LinuxStandaloneSupport/Variations/linux64_player_nondevelopment_mono
79 UNITY_VER=2021.3.19f1
80 UNITY_INSTALLER_URL=https://download.unity3d.com/download_unity/019e31cfdb15/LinuxEditorInstaller/Unity-$UNITY_VER.tar.xz

106 [ ! -f "tmp/Unity.tar.xz" ] && wget -O ./tmp/Unity.tar.xz $UNITY_INSTALLER_URL
```

This is what worked for me, with the disclaimer that I messed up line 106 and had to move a file manually, but I think this version should work now, just haven't tested.
Also, if you already have the update hearthstone version, but not the updated Unity version, you need to delete the `hearthstone` folder before running craft.sh (you could also edit the script [e.g., commenting out lines 84-87], but just deleting and reinstalling hearthstone is probably the simplest way to do it).

**Comment by 0xf4b1** [comment]
Works fine for me with the changes, thanks! I've updated the script in the repo.

If you update from a previous version, just remove the following in the hearthstone directory so that the script will download the unity files agian:

```
rm Bin/Hearthstone.x86_64
rm Bin/UnityPlayer.so
rm -rf Bin/Hearthstone_Data/MonoBleedingEdge/
```

If you have updated already, you can analogously download and extract and these files from the tarball into the directory manually.
