### ISSUE TITLE
Unity version was updated (Patch 26.6)

### ISSUE THREAD

**Issue by jbakes89** [0xf4b1/hearthstone-linux#40]
It seems like they silently updated the Unity version in the latest path (26.6 - adding new Twist mode, announcement of Titans, etc.).

The new version is 2021.3.25f1 and the download link is https://download.unity3d.com/download_unity/68ef2c4f8861/LinuxEditorInstaller/Unity.tar.xz.

For people coming to this before the main branch gets updated, you need to update the version and download link in 'craft.sh' as given above, and delete three files/directories before running craft.sh, to make sure they get update to the new Unity version:
Bin/Hearthstone.x86_64
Bin/UnityPlayer.so
Bin/Hearthstone_Data/MonoBleedingEdge/

Refer here for more detailed instructions from last time there was a similar issue: [https://github.com/0xf4b1/hearthstone-linux/issues/37#issuecomment-1542814830](https://github.com/0xf4b1/hearthstone-linux/issues/37#issuecomment-1542814830)

**Comment by 0xf4b1** [comment]
Hey, thanks for reporting this, I can not test rn, but if its working fine for you, feel free to create a PR :)

**Comment by orlin777** [comment]
It works for me with the version mentioned above, but the directory structure of Unity must have changed.
just backup your hearthstone/token
rm -rf hearthstone
./craft.sh
copy your token back

**Comment by 0xf4b1** [comment]
With #46 merged, it should now be updated to work with the latest game version
