### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by SlikeDollar** [0xf4b1/hearthstone-linux#41]
I did everything step by step according to readme. tried launching the game and got [this](https://pastebin.com/29EhZGjx).The game doesn't launch. I looked for issues and changed everything according to the #40 but output remains the same

**Comment by jbakes89** [comment]
If you check `~/.config/unity3d/Blizzard Entertainment/Hearthstone/Player.log`, the error messages are often pretty self-explanatory.

If you try launching the game, then post the contents of the `Player.log` file here, I could have a look for you.

In the meantime, one thing that happened to me was the `MonoBleedingEdge` folder stayed in the `hearthstone` folder, when it should have been moved to `.../hearthstone/Bin/Hearthstone_Data/`. I don't know why this was happening, but you could check that an move the folder manually if you need to.
If that's the problem, the log file will probably say something about being unable to load `...MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so`

**Comment by SlikeDollar** [comment]
fixed this issue after deleting hearthstone folder and running craft.sh again 😄
