### ISSUE TITLE
Preparation step update for ubuntu

### ISSUE THREAD

**Issue by poulwann** [0xf4b1/hearthstone-linux#48]
Hi,

When using the instructions as is in the readme, this will not work due to:
```
Creating python venv for keg ...
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.11-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
```

The Python3.11-venv needs to be added to the preparation section under Ubuntu (I haven't tested on Debian, but afaik venv is not a part of the python3 default meta packages there either).

When I ran the craft.sh without this package, some artifacts was created which prevented the venv to be properly created even after installing the venv package. This might be non obvious to rectify for new users.

**Comment by 0xf4b1** [comment]
Hey, thanks for pointing that out, I'll quickly update the required packages
