### ISSUE TITLE
Doesn’t start after latest update

### ISSUE THREAD

**Issue by alterNERDtive** [0xf4b1/hearthstone-linux#55]
Well, title. Had to update today, now it just prints out Unity configuration and exits(1).

No idea how to even start troubleshooting this :)

**Comment by xtecox** [comment]
Same here:

Region: us
Online version: 28.4.0.192412
Installed version: 28.4.0.192412
strings: 'Hearthstone.app/Contents/Resources/Data/level0': Não é esse arquivo
Can not determine required Unity version!

**Comment by 0xf4b1** [comment]
I did a quick check and get the following in the unity log file from `~/.config/unity3d/Blizzard Entertainment/Hearthstone/Player.log`

```
Mono path[0] = '/mnt/fabi/repo/hearthstone-linux/hearthstone/Bin/Hearthstone_Data/Managed'
Mono config path = '/mnt/fabi/repo/hearthstone-linux/hearthstone/Bin/Hearthstone_Data/MonoBleedingEdge/etc'
Preloaded 'CoreFoundation.so'
Preloaded 'libOSXWindowManagement.so'
Preloaded 'libblz_commerce_sdk_plugin.so'
Display 0 'XWAYLAND0 27"': 2560x1440 (primary device).
Desktop is 2560 x 1440 @ 165 Hz
Unknown renderer 16
No supported renderers found, exiting
```

The last two lines unfortunately say that there is no more supported renderer, so it seems they have now dropped OpenGL support from the macOS client and only support metal (renderer 16) which means this method no longer works :(

If the mac or windows clients would be shipped with Vulkan support, it should continue to work, so a quick check with the Windows client gives the following: 

```
Mono path[0] = '/home/fabi/Hearthstone/Hearthstone_Data/Managed'
Mono config path = '/home/fabi/Hearthstone/Hearthstone_Data/MonoBleedingEdge/etc'
Display 0 'XWAYLAND0 27"': 2560x1440 (primary device).
Desktop is 2560 x 1440 @ 165 Hz
Unknown renderer 2
No supported renderers found, exiting
```

Also sadly nothing changed, it only comes with support for DirectX (renderer 2) :(

**Comment by Starfight** [comment]
Not a real solution but for the moment I use Wine to play, installed with this instructions: https://github.com/borisbabic/hearthstone_hdt_linux

It was more unstable than this one before the patch, but I played today and I had less issues.

**Comment by Josee9988** [comment]
Same here

**Comment by alterNERDtive** [comment]
Noticed there was an update to HS today and … drumroll … it works again!

I just hope they’ll keep the OpenGL renderer now :<

**Comment by 0xf4b1** [comment]
Awesome! :tada: it works again! Let's hope the renderer was rather accidentally disabled than intentionally and that it will remain enabled for a long time :D

**Comment by alterNERDtive** [comment]
Seems like they removed OpenGL again :-/

**Comment by xtecox** [comment]
Ive deleted hearthstone folder and runned ./craft.sh again, it worked

**Comment by alterNERDtive** [comment]
There has been an update in the meantime; can confirm it works again.

It seems like Blizzard needs to get their build pipeline in order.

**Comment by alterNERDtive** [comment]
I have this issue again; but instead of immediately closing, I get an infinite black screen.

**Comment by alterNERDtive** [comment]
… aaaaand it works again after the latest update. Didn’t change anything on my end or reinstall.
