### ISSUE TITLE
Error when extracting downloaded Unity files

### ISSUE THREAD

**Issue by AdventureT** [0xf4b1/hearthstone-linux#61]
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Unity.tar.xz:
```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details></Error>
```

**Comment by AdventureT** [comment]
Seems like they changed the filename, which includes the version number now.
https://download.unity3d.com/download_unity/68ef2c4f8861/LinuxEditorInstaller/Unity-2021.3.25f1.tar.xz

**Comment by Devorlon** [comment]
I've also encountered this. Same error:

```
Extracting Unity files ...
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by 0xf4b1** [comment]
hmm, the url still works fine for me in browser and also with `curl https://download.unity3d.com/download_unity/68ef2c4f8861/LinuxEditorInstaller/Unity.tar.xz -o Unity.tar.xz` :thinking:

**Comment by LevBernstein** [comment]
Happened for me as well:
```
Fetching Unity archive ...
Downloading Unity files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    150      0  0:00:01  0:00:01 --:--:--   150
Extracting Unity files ...
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by Themanwhosmellslikesugar** [comment]
Same error, running on Kubuntu 22.04

**Comment by fromgate** [comment]
I meet the same problem:

Required Unity version: 2021.3.39f1
Installed Unity version: Not installed
Update required.
~/hearthstone-linux/hearthstone/tmp ~/hearthstone-linux/hearthstone ~/hearthstone-linux
Fetching Unity archive ...
Downloading Unity files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0     95      0  0:00:03  0:00:03 --:--:--    95
Extracting Unity files ...
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by 0xf4b1** [comment]
the parsing of one part of the unity download url was buggy, it should be fixed now and work again :)

**Comment by alterNERDtive** [comment]
I wasn’t affected by this in particular, but thanks for keeping this project going <3
