### ISSUE TITLE
Error in CoreFoundation.c 

### ISSUE THREAD

**Issue by MegaSergun** [0xf4b1/hearthstone-linux#63]
During a clean install (running craft.sh) after extracting and moving unity file I get an error in CoreFoundation.c

Moving files & running cleanup ...
Cleaning up unecessary files ...
/run/media/sergun/extra/Games/Standalone/hearthstone-linux
make: Entering directory '/run/media/sergun/extra/Games/Standalone/hearthstone-linux/login'
g++ login.c -lcryptopp `pkg-config  --libs gtk+-3.0 webkit2gtk-4.0` `pkg-config --cflags gtk+-3.0 webkit2gtk-4.0` -o login
make: Leaving directory '/run/media/sergun/extra/Games/Standalone/hearthstone-linux/login'
make: Entering directory '/run/media/sergun/extra/Games/Standalone/hearthstone-linux/stubs'
gcc -O2 -fPIC -shared -o CoreFoundation.so CoreFoundation.c
CoreFoundation.c: In function 'CFDataGetBytePtr':
CoreFoundation.c:27:10: error: returning 'char *' from a function with return type 'intptr_t' {aka 'long int'} makes integer from pointer without a cast [-Wint-conversion]
   27 |   return buffer;
      |          ^~~~~~
make: *** [Makefile:9: CoreFoundation.so] Error 1
make: Leaving directory '/run/media/sergun/extra/Games/Standalone/hearthstone-linux/stubs'

**Comment by 0xf4b1** [comment]
I've added the missing cast with https://github.com/0xf4b1/hearthstone-linux/commit/7a40b19309f3b2a70e31d173a6d416e4d395a9a9, please try again with this change :)

**Comment by MegaSergun** [comment]
> I've added the missing cast with [7a40b19](https://github.com/0xf4b1/hearthstone-linux/commit/7a40b19309f3b2a70e31d173a6d416e4d395a9a9)
That was it, many thanks! Now the installer finishes with no errors and the game works.
