### ISSUE TITLE
Development Environment/CONTRIBUTING

### ISSUE THREAD

**Issue by rflandau** [0xf4b1/hearthstone-linux#64]
Would you post your set up development environment and/or recommendations for contribution? Coming from pure C99+Clang, having some trouble setting up a workable environment with your c(++?) files.

This is related to creating a fix for the segfault that occurs if login is called outside of the immediate directory.

**Comment by 0xf4b1** [comment]
All the things here are kept very simple, the source of the login app is only the login.c, I use vscode personally to do my changes and build with make

**Comment by rflandau** [comment]
Interesting. I must be missing some libraries.
Thanks.

**Comment by 0xf4b1** [comment]
If you already installed hearthstone successfully with the craft script, you should actually have everything you need as it includes the building of the login app :thinking:

and regarding the path sensitive segfault you describe, I'm wondering a bit what problem you faced, actually it only creates the token file in the current working directory which is why you should actually run it inside the hearthstone directory where it is expected to be present

**Comment by rflandau** [comment]
You are right, I do. I needed to put together a g++ configuration for the language server to be usable and g++ is a little different than my usual Clang (and it got confused by the .c, rather than .cpp extensions). Switching to .cpp and using the below `c_cpp_properties.json` file appears to have done the trick for now. By default, the includes are not searching/adding recursively as I didn't find I needed it in bare C.
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/12",
                "/usr/include/x86_64-linux-gnu/c++/12",
                "/usr/include/c++/12/backward",
                "/usr/lib/gcc/x86_64-linux-gnu/12/include",
                "/usr/local/include",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "${workspaceFolder}/**",
                "/usr/include/gtk-3.0",
                "/usr/include/webkitgtk-4.0",
                "/usr/include/glib-2.0",
                "/usr/include/libsoup-2.4",
                "/usr/include/cairo",
                "/usr/lib/x86_64-linux-gnu/glib-2.0/include",
                "/usr/include/pango-1.0",
                "/usr/include/harfbuzz"
            ],
            "defines": [],
            "cStandard": "c17",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-clang-x64",
            "compilerArgs": []
        }
    ],
    "version": 4
}
```

As for the segfault, yes, the code currently works if run from the specified directory. It segfaults at the login.c:56, the `fwrite` I'd like to see if I can make it more flexible, but will have to come take another look after work.

**Comment by 0xf4b1** [comment]
Ah okay, this makes sense, if you run the app from some other directory without write permission, the fopen and fwrite will fail. Would possibly be smarter to make sure to write the file into the directory in which the app itself is located, then you can run it from everywhere, but remember this is only a one-shot app, once you have the token, you never need to run it again
