### ISSUE TITLE
libwebkit2gtk-4.0-dev not in Ubuntu 24.04

### ISSUE THREAD

**Issue by s2hsieh** [0xf4b1/hearthstone-linux#68]
I do know how to get around this. But, correct me if I'm wrong, webkit is only used to render the login page and then fetching the token that gets generated, right? You probably won't have to worry about it braking if someone has libwebkit2gtk-4.x-dev installed instead of 4.0 specifically. 
And yes, I understand the issue is that each version has it's own package name, instead of just the same package name with versioning. Perhaps  some pattern matching like "libwebkit2gtk-4(\.\d)*?-dev" can help.

Apologies if I'm totally off base. I'm just trying to think of ways to make this more resilient and less work to maintain.

Loving the work you all have done by the way, I had almost given up getting Hearthstone running on Linux, before I stumbled on this today. I had assumed wine or some sort of android emulation was the only way to go, and they never quite work. So imagine my surprise to see it can be run natively by running the OSX version of Hearthstone using the Linux version of Unity, genius!

**Comment by 0xf4b1** [comment]
Hey, yes you're right, the tool is just to load the login page and fetch the token and as it never expires, you don't need to use it again. It was contributed and I've added the crypto stuff. Before it existed, you had to visit the web page in any browser and paste the token to c# tool in `token` folder which is mainly extracted from the unity code of the game.

I have made some small changes based on your suggestion to make it less dependant on the version :)
