### ISSUE TITLE
Hello a little problem with login function i ll just take a look 

### ISSUE THREAD

**Issue by ripitchip** [0xf4b1/hearthstone-linux#69]
Hi I just found a bug, I ll send a patch if I find a solution xD
Thank you for this awesome repo ^^
Info:
os: arch
gtk2, gtk 3 gtk 4 installed and libcrypto also (path is incorrect -> *need to fix the make file*)

g++ login.c `pkg-config --cflags --libs gtk+-3.0 libcrypto++ webkit2gtk-4.0` -o login
Package libcrypto++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto++.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libcrypto++', required by 'virtual:world', not found
login.c:5:10: fatal error: gtk/gtk.h: No such file or directory
    5 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:18: login] Error 1

**Comment by ripitchip** [comment]
Found !!!
On arch libcrypto++ is named libcryptopp
I ll make a little script getting if is is a debian base or arch base if you want?
Do you authorize pull request?

**Comment by 0xf4b1** [comment]
ooups, with my last change I actually wanted to make it cleaner to get the libcrypto++ flags from pkg-config but then it seems to be not consistent across distributions :smiling_face_with_tear: before there was simply `-lcryptopp` added as flag and seemed to work for all so I can simply change this back
