### ISSUE TITLE
Script cannot fetch Unity

### ISSUE THREAD

**Issue by friend360** [0xf4b1/hearthstone-linux#75]
I have this for a while and my game update as it should, but my friend cannot build it, got this error: "Unity version not found in archive".
I've tried it in new folder and get same error.

**Comment by sepiatonal** [comment]
I'm getting this as well.

**Comment by sepiatonal** [comment]
As a workaround, I was able to fix it by manually installing Unity 2021.3.40f1 through UnityHub.

**Comment by waterfox22** [comment]
same, thanks to @sepiatonal for a workaround
