### ISSUE TITLE
native Wayland support

### ISSUE THREAD

**Issue by alterNERDtive** [0xf4b1/hearthstone-linux#76]
Is there a way to have the game run on Wayland natively instead of XWayland?

The immediate issue that would solve for me is actually running in 4k on a 2x scaled display. XWayland thinks it’s 1080p because of the scaling.

**Comment by alterNERDtive** [comment]
Setting `SDL_VIDEODRIVER=wayland` works. Sadly the game still doesn’t go beyond 1080p, but that appears to be a separate issue then.

**Comment by 0xf4b1** [comment]
I have no idea about the scaling issues but regarding wayland, I just read about the `-force-wayland` flag [here](https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html), not sure if this does something different compared to the env variable you found.

**Comment by alterNERDtive** [comment]
AFAI can see the flag does the same thing as setting the environment variable.
