### ISSUE TITLE
Unreleased patch 21.6 will use newer Unity

### ISSUE THREAD

**Issue by justinkb** [0xf4b1/hearthstone-linux#8]
Opening this issue prematurely so you are aware

**Comment by justinkb** [comment]
Seems to be using 2019.4.21f1

**Comment by 0xf4b1** [comment]
That's right, only needs updated unity files. Got it running already and will push the update shortly :)

**Comment by justinkb** [comment]
confirming this is working fine for me as well, issue can be closed

**Comment by 0xf4b1** [comment]
Okay, great :)

**Comment by justinkb** [comment]
when I've now tried this with the Unity.tar.xz downloaded via wget, I ran into

```
cp: cannot stat 'tmp/Editor/Data/PlaybackEngines/LinuxStandaloneSupport/Variations/linux64_withgfx_nondevelopment_mono/UnityPlayer.so': No such file or directory
```

**Comment by 0xf4b1** [comment]
Yes, you are right, I missed this one.
